routes/web.php
<?php

use App\Http\Controllers\WordController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

// Form Builder
Route::resource('builder', 'BuilderController');

Route::middleware('auth')->group(function () {
    Route::get('/', 'HomeController@index')->name('home');

    Route::resource('shifts', 'ShiftController');

    Route::resource('events', 'EventController');

    Route::get('lines/{status}', 'LineController@index')->where('status', '(live|closed)')->name('lines.status');
    Route::resource('lines', 'LineController');

    Route::get('equipements/{status}', 'EquipementController@index')->where('status', '(live|closed)')->name('equipements.status');
    Route::resource('equipements', 'EquipementController');

    Route::get('/contact-us', 'ContactusController@create')->name('contactus.create');
    Route::post('/contact-us', 'ContactusController@store')->name('contactus.store');

    Route::get('profile', 'ProfileController@show')->name('profile.show');
    Route::put('profile', 'ProfileController@update')->name('profile.update');
    Route::get('password', 'ProfileController@password')->name('profile.password');
    Route::put('password', 'ProfileController@passUpdate')->name('profile.passUpdate');

    Route::middleware('can:supervise')->prefix('supervision')->group(function () {
        Route::get('events', 'SupervisionController@events')->name('supervision.events');
        Route::get('lines', 'SupervisionController@lines')->name('supervision.lines');
        Route::get('equipements', 'SupervisionController@equipements')->name('supervision.equipements');
    });

    Route::prefix('reports')->group(function () {
        Route::view('/tables/lines', 'reports.lines')->name('reports.index');
        Route::get('/tables/data/{objet}', 'ReportController@datatable')->name('reports.data');
        Route::resource('indicators', 'IndicatorController');
        Route::post('indicators/{indicator}', 'IndicatorController@show')->name('reports.data');
    });

    Route::resource('objets', 'ObjetController');
    // Route::resource('subobjets', 'SubobjetController');
    Route::resource('objets.subobjets', 'SubobjetController');
    Route::resource('reports', 'ReportController');
});

Route::middleware('can:admin')->prefix('admin')->group(function () {
    // Messages
    Route::resource('messages', 'MessageController');
    // Route::get('messages', 'ContactusController@index')->name('contactus.index');
    // Users
    Route::resource('users', 'UserController');
    // Entities
    Route::resource('entities', 'EntityController');
    // Roles
    Route::resource('roles', 'RolesController');
    // Abilities
    Route::resource('abilities', 'AbilityController');
    Route::resource('cruds', 'CrudController');
    Route::get("import", "ImportController@create")->name('import.create');
    Route::post("import", "ImportController@parse")->name('import.parse');
    Route::post("import/process", "ImportController@process")->name('import.process');
});

// Route::get('allusers', 'UsersController@datatable');
Auth::routes();

Route::get('/logout', function () {
    Auth::logout();
    return redirect()->route('login');
});

// Route::view('avatarr', 'profiles.avatar');
// Route::view('test', 'test');
Route::get('/indicator/data/{objet}/{year}/{month}', "IndicatorController@data");
Route::view('/lolo', 'login');
Route::get("cmd", "TestController@command");
Route::get("test", "TestController@factors");
Route::view("icons", "pages.icons");
Route::get("add", "ShiftController@add");
Route::view('toto', 'tests.login3');
Route::get('/word', 'WordController@createWordDocument');

app/Line.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Line extends Model
{
    protected $guarded = ['id'];
    protected $dates = ['start_time', 'end_time'];
    const TYPES_SELECT = ['corr' => 'Corrective', 'prev' => 'Preventive'];

    public function subobjet()
    {
        return $this->belongsTo(Subobjet::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function objet()
    {
        return $this->belongsTo(Objet::class);
    }

    public function entity()
    {
        return $this->belongsTo(Entity::class);
    }
}

app/Http/Controllers/LineController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreLineRequest;
use App\Http\Requests\UpdateLineRequest;
use Illuminate\Support\Carbon;
use App\Line;
use Illuminate\Http\Request;

class LineController extends Controller
{
    // public function index()
    // {
    //     $lines = entity()->lines();
    //     if (request('status') == 'live') $lines = $lines->whereNull('end_time');
    //     $lines = $lines->paginate(10);

    //     return view('lines.index', compact('lines'));
    // }

    public function index(Request $request)
    {
        $lines = entity()->lines();

        if ($request->has('objet')) {
            $lines->where('objet_id', $request->objet);
        }
        if ($request->has('subobjet')) {
            $lines->where('subobjet_id', $request->subobjet);
        }
        if (request('status') == 'live') $lines = $lines->whereNull('end_time');
        $lines = $lines->paginate(10);

        return view('lines.index', compact('lines'));
    }


    public function create()
    {
        $objets = entity()->objets->where('type_id', 2); /* Select Lines */
        $subobjets = $objets->first()->subobjets->pluck('name', 'id'); /* Select the first element for select input */
        $objets = $objets->pluck('name', 'id');

        return view('lines.create', compact('objets', 'subobjets'));
    }


    public function store(StoreLineRequest $request)
    {
        $user = me();
        $data = $request->only(['comment', 'subobjet_id', 'type', 'objet_id']);
        $data['user_id'] = $user->id;
        $data['entity_id'] = $user->entity_id;
        $data['start_time'] = "{$request['startdate']} {$request['starttime']}";
        Line::create($data);

        return redirect()->route('lines.index');
    }

    public function show(Line $line)
    {
        $objets = entity()->objets->where('type_id', 2)->pluck('name', 'id');
        $subobjets = $line->objet->subobjets->pluck('name', 'id');

        return view('lines.close', compact('line', 'objets', 'subobjets'));
    }


    public function edit(Line $line)
    {
        $objets = entity()->objets->where('type_id', 2)->pluck('name', 'id');
        $subobjets = $line->objet->subobjets->pluck('name', 'id');

        return view('lines.edit', compact('line', 'objets', 'subobjets'));
    }

    public function update(UpdateLineRequest $request, Line $line)
    {
        $user = me();
        $data = $request->only(['comment', 'subobjet_id', 'type', 'objet_id']);
        $data['user_id'] = $user->id;
        $data['entity_id'] = $user->entity_id;
        $data['start_time'] = Carbon::parse("{$request->startdate} {$request->starttime}");

        if (isset($request->endtime) and isset($request->enddate)) {
            $data['end_time'] = Carbon::parse("{$request->enddate} {$request->endtime}");
            $data['duration'] = $data['start_time']->diffInMinutes($data['end_time']);
            $data['status'] = 'closed';
        }

        $line->update($data);
        return redirect()->route('lines.index');
    }


    public function destroy(Line $line)
    {
        $line->delete();
        return redirect()->route('lines.index');
    }
}

resources/views/lines/close.blade.php
<x-form icon="/svg/001.svg" :action="route('lines.update',$line)" title="Mise en service">
  @method('PUT')
  <div class="form-row">
    <div class="form-group col-md-5">
      <label>Objet :</label>
      <select name="objet_id" class="form-control select2" id="objet" placeholder="Selectioner un objet">
        {!! options($objets, $line->objet_id) !!}
      </select>
    </div>
    <div class="form-group col-md-4">
      <label for="topic">Sous-objet :</label>
      <select class="form-control select2" name="subobjet_id" id="subobj" required>
        {!! options($subobjets, $line->subobjet_id) !!}
      </select>
    </div>
    <div class="form-group col-md-3">
      <label for="title">Type :</label>
      <select name="type" id="type" class="form-control select2">
        {!! options(App\Line::TYPES_SELECT,$line->type) !!}
      </select>
    </div>

  </div>
  <div class="hr-fancy"></div>
  <div class="form-row">
    <div class="form-group col-md-4">
      <label for="language">Date d'arrêt:</label>
      <input type="date" class="form-control" name="startdate" value="{{ $line->start_time->format('Y-m-d') }}" required>
    </div>
    <div class="form-group col-md-3">
      <label for="language">Heure d'arrêt:</label>
      <input name="starttime" type="time" class="form-control" value="{{ $line->start_time->format("H:i") }}" required>
    </div>
  </div>
  <div class="form-row">
    <div class="form-group col-md-4">
      <label for="language">Date de reprise:</label>
      <input type="date" class="form-control" name="enddate" required>
    </div>
    <div class="form-group col-md-3">
      <label for="language">Heure de reprise:</label>
      <input name="endtime" type="time" class="form-control" required>
    </div>
  </div>
  <div class="form-row">
    <div class="form-group col-md-12">
      <label for="event">Commentaire :</label>
      <textarea class="form-control" name="comment" rows="3">{{ $line->comment ?? '' }}</textarea>
    </div>
  </div>
  <button type="submit" class="btn btn-dark"><span class="fa fa-play mr-2"></span>Mise en service</button>
</x-form>

resources/views/lines/create.blade.php
<x-form icon="/svg/001.svg" :action="route('lines.store')" title="Ajouter un nouveau">

  <div class="form-row">
    <div class="form-group col-md-5">
      <label>Objet :</label>
      <select name="objet_id" class="form-control select2" id="objet" placeholder="Selectioner un objet">
        {!! options($objets) !!}
      </select>
    </div>
    <div class="form-group col-md-4">
      <label for="topic">Sous-objet :</label>
      <select class="form-control select2" name="subobjet_id" id="subobj" required>
        {!! options($subobjets) !!}
      </select>
    </div>
    <div class="form-group col-md-3">
      <label for="title">Type :</label>
      <select name="type" id="type" class="form-control select2">
        {!! options(App\Line::TYPES_SELECT) !!}
      </select>
    </div>

  </div>
  <div class="hr-fancy"></div>
  <div class="form-row">
    <div class="form-group col-md-4">
      <label for="language">Date d'arrêt:</label>
      <input type="date" class="form-control" name="startdate" value="{{ old('startdate') ?? date('Y-m-d') }}" required>
    </div>
    <div class="form-group col-md-3">
      <label for="language">Heure d'arrêt:</label>
      <input name="starttime" type="time" class="form-control" value="{{ old('starttime') ?? date('H:i') }}" required>
    </div>
  </div>
  <div class="form-row">
    <div class="form-group col-md-12">
      <label for="event">Commentaire :</label>
      <textarea class="form-control" name="comment" rows="3"></textarea>
    </div>
  </div>

  <button type="submit" class="btn btn-primary"><span class="fa fa-plus mr-2"></span>Ajouter</button>
</x-form>

resources/views/lines/edit.blade.php
<x-form icon="/svg/001.svg" :action="route('lines.update',$line)" title="Modifier">
  @method("PUT")

  <div class="form-row">
    <div class="form-group col-md-5">
      <label>Objet :</label>
      <select name="objet_id" class="form-control select2" id="objet" placeholder="Selectioner un objet">
        {!! options($objets, $line->objet_id) !!}
      </select>
    </div>
    <div class="form-group col-md-4">
      <label for="topic">Sous-objet :</label>
      <select class="form-control select2" name="subobjet_id" id="subobj" required>
        {!! options($subobjets, $line->subobjet_id) !!}
      </select>
    </div>
    <div class="form-group col-md-3">
      <label for="title">Type :</label>
      <select name="type" id="type" class="form-control select2">
        {!! options(App\Line::TYPES_SELECT,$line->type) !!}
      </select>
    </div>

  </div>
  <div class="hr-fancy"></div>
  <div class="form-row">
    <div class="form-group col-md-4">
      <label for="language">Date d'arrêt:</label>
      <input type="date" class="form-control" name="startdate" value="{{ $line->start_time->format('Y-m-d') }}" required>
    </div>
    <div class="form-group col-md-3">
      <label for="language">Heure d'arrêt:</label>
      <input name="starttime" type="time" class="form-control" value="{{ $line->start_time->format("H:i") }}" required>
    </div>
  </div>
  @if($line->end_time)
  <div class="form-row">
    <div class="form-group col-md-4">
      <label for="language">Date de reprise:</label>
      <input type="date" class="form-control" name="enddate" value="{{ $line->end_time->format('Y-m-d') }}" required>
    </div>
    <div class="form-group col-md-3">
      <label for="language">Heure de reprise:</label>
      <input name="endtime" type="time" class="form-control" value="{{ $line->end_time->format('H:i') }}" required>
    </div>
  </div>
  @endif
  <div class="form-row">
    <div class="form-group col-md-12">
      <label for="event">Commentaire :</label>
      <textarea class="form-control" name="comment" rows="3">{{ $line->comment ?? '' }}</textarea>
    </div>
  </div>

  <button type="submit" class="btn btn-success">
    <span class="fa fa-edit mr-2"></span>Modifier
  </button>

</x-form>

resources/views/lines/index.blade.php
@extends('layouts.admin')

@section('title', 'Les arrêts et les coupures')

@section('content')
<x-pages-card icon="/svg/001.svg" :link="route('lines.create')" button="Ajouter un nouveau" :items="$lines">

  <thead class="">
    <tr>
      <th class="text-center" style="width:200px">Objet</th>
      <th class="text-center" style="width:100px">Debut</th>
      <th class="text-center" style="width:100px">Fin</th>
      <th>Commentaire</th>
      <th class="text-center" style="width:100px">Créé par</th>
      <th class="text-center" style="width:150px">Actions</th>
    </tr>
  </thead>

  <tbody>
    @foreach ($lines as $line)
    <tr>
      <td class="text-center">
        <a href="{{ route('lines.index',['objet' => $line->objet_id]) }}">{{ $line->objet->name }}</a>
        <br />
        <a href="{{ route('lines.index',['subobjet' => $line->subobjet_id]) }}">{{ $line->subobjet->name }}</a>
      </td>
      <td class="text-center">{{ $line->start_time->format("H:i") }}<br /><small>{{ $line->start_time->format("d-m-Y") }}</small></td>
      <td class="text-center">
        @if($line->end_time)
        {{ $line->end_time->format("H:i") }}<br /><small>{{ $line->end_time->format("d-m-Y") }}</small>
        @else
        -----
        @endif
      </td>
      <td class="event text-left p-2"> {!! markdown($line->comment,false) !!} </td>
      <td class="text-center">
        <span class="badge badge-dark text-sm">
          {{ $line->user->username }}
        </span>
      </td>
      <td class="text-center">
        @unless($line->end_time)
        <a class="btn btn-success btn-sm" title="Mise en service" href="{{ route('lines.show',$line->id) }}"> <i class="fas fa-check-circle"> </i> </a>
        @endif
        <a class="btn btn-info btn-sm" title="Éditer" href="{{ route('lines.edit',$line->id) }}"> <i class="fas fa-pencil-alt"> </i> </a>
        <a class="btn btn-danger btn-sm" title="Supprimer" href="#" data-url="{{ route('lines.destroy',$line) }}" onclick="deleteData(this)">
          <i class="fas fa-trash"></i>
        </a>
      </td>
    </tr>
    @endforeach
  </tbody>

</x-pages-card>
@endsection