routes/web.php
<?php

use App\Http\Controllers\WordController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

// Form Builder
Route::resource('builder', 'BuilderController');

Route::middleware('auth')->group(function () {
    Route::get('/', 'HomeController@index')->name('home');

    Route::resource('shifts', 'ShiftController');

    Route::resource('events', 'EventController');

    Route::get('lines/{status}', 'LineController@index')->where('status', '(live|closed)')->name('lines.status');
    Route::resource('lines', 'LineController');

    Route::get('equipements/{status}', 'EquipementController@index')->where('status', '(live|closed)')->name('equipements.status');
    Route::resource('equipements', 'EquipementController');

    Route::get('/contact-us', 'ContactusController@create')->name('contactus.create');
    Route::post('/contact-us', 'ContactusController@store')->name('contactus.store');

    Route::get('profile', 'ProfileController@show')->name('profile.show');
    Route::put('profile', 'ProfileController@update')->name('profile.update');
    Route::get('password', 'ProfileController@password')->name('profile.password');
    Route::put('password', 'ProfileController@passUpdate')->name('profile.passUpdate');

    Route::middleware('can:supervise')->prefix('supervision')->group(function () {
        Route::get('events', 'SupervisionController@events')->name('supervision.events');
        Route::get('lines', 'SupervisionController@lines')->name('supervision.lines');
        Route::get('equipements', 'SupervisionController@equipements')->name('supervision.equipements');
    });

    Route::prefix('reports')->group(function () {
        Route::view('/tables/lines', 'reports.lines')->name('reports.index');
        Route::get('/tables/data/{objet}', 'ReportController@datatable')->name('reports.data');
        Route::resource('indicators', 'IndicatorController');
        Route::post('indicators/{indicator}', 'IndicatorController@show')->name('reports.data');
    });

    Route::resource('objets', 'ObjetController');
    // Route::resource('subobjets', 'SubobjetController');
    Route::resource('objets.subobjets', 'SubobjetController');
    Route::resource('reports', 'ReportController');
});

Route::middleware('can:admin')->prefix('admin')->group(function () {
    // Messages
    Route::resource('messages', 'MessageController');
    // Route::get('messages', 'ContactusController@index')->name('contactus.index');
    // Users
    Route::resource('users', 'UserController');
    // Entities
    Route::resource('entities', 'EntityController');
    // Roles
    Route::resource('roles', 'RolesController');
    // Abilities
    Route::resource('abilities', 'AbilityController');
    Route::resource('cruds', 'CrudController');
    Route::get("import", "ImportController@create")->name('import.create');
    Route::post("import", "ImportController@parse")->name('import.parse');
    Route::post("import/process", "ImportController@process")->name('import.process');
});

// Route::get('allusers', 'UsersController@datatable');
Auth::routes();

Route::get('/logout', function () {
    Auth::logout();
    return redirect()->route('login');
});

// Route::view('avatarr', 'profiles.avatar');
// Route::view('test', 'test');
Route::get('/indicator/data/{objet}/{year}/{month}', "IndicatorController@data");
Route::view('/lolo', 'login');
Route::get("cmd", "TestController@command");
Route::get("test", "TestController@factors");
Route::view("icons", "pages.icons");
Route::get("add", "ShiftController@add");
Route::view('toto', 'tests.login3');
Route::get('/word', 'WordController@createWordDocument');

app/Objet.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Objet extends Model
{
    protected $guarded = ['id'];

    public function entity()
    {
        return $this->belongsTo(Entity::class);
    }

    const STATUS_SELECT = [
        'active' => 'Actif',
        'passive' => 'Passif'
    ];

    public function subobjets()
    {
        return $this->hasMany(Subobjet::class)->where('status', 'active');
        // ->orderBy('name', 'ASC');
    }

    public function type()
    {
        return $this->belongsTo(Type::class);
    }

    public function events()
    {
        return $this->hasManyThrough(Event::class, Subobjet::class);
    }
}

app/Http/Controllers/ObjetController.php
<?php

namespace App\Http\Controllers;

use App\Entity;
use App\Http\Controllers\Controller;
use App\Http\Requests\StoreObjetRequest;
use App\Objet;
use App\Type;
use Illuminate\Support\Facades\File;
// use File;
use Illuminate\Support\Facades\Gate;

class ObjetController extends Controller
{
    public function index()
    {
        $type = request()->query('type', 1);
        if (Gate::allows('admin')) {
            $objets = Objet::where('type_id', $type)->with('entity', 'type')->get();
        } else {
            $objets = me()->entity->objets()->where('type_id', $type)->with('entity')->get();
        }
        return view('objets.index', compact('objets'));
    }

    public function create()
    {
        $entities = Entity::all()->pluck('label', 'id');
        $types = Type::all()->pluck('label', 'id');
        return view('objets.create', compact('entities', 'types'));
    }

    public function store(StoreObjetRequest $request)
    {
        // Add Entity if not admin
        if (Gate::denies('admin'))
            $request['entity_id'] = me()->entity->id;
        $objet = Objet::create($request->all());
        return redirect()->route('objets.index');
    }

    public function edit(Objet $objet)
    {
        // $avatars = ['001.svg', '002.svg'];
        $path = public_path('svg');
        $files = File::files($path);
        $avatars = [];
        foreach ($files as $file) {
            $avatars[] = pathinfo($file)['basename'];
        }
        return view('objets.edit', compact('objet', 'avatars'));
    }

    public function update(StoreObjetRequest $request, Objet $objet)
    {
        $objet->update($request->all());
        // return redirect()->route('objets.index');
        return back();
    }

    public function show(Objet $objet)
    {
        return view('objets.show', compact('objet'));
    }

    public function destroy(Objet $objet)
    {
        $objet->delete();
        return back();
    }
}

resources/views/objets/create.blade.php
<x-form title="Créer un nouveau objet" :action="route('objets.store')">
  <div class="form-row">
    <div class="col-md-6">
      <div class="form-group">
        <label class="required" for="type_id">Le type d'objet</label>
        <select class="form-control select2 {{ $errors->has('type_id') ? 'is-invalid' : '' }}" name="type_id" id="type_id" required>
          @foreach($types as $key => $value)
          <option value="{{ $key }}" {{ old('type_id') == $key ? 'selected' : '' }}>{{ $value }}</option>
          @endforeach
        </select>
        @if($errors->has('type_id'))
        <span class="text-danger">{{ $errors->first('type_id') }}</span>
        @endif
      </div>
    </div>
    @can('admin')
    <div class="col-md-4">
      <div class="form-group">
        <label class="required" for="entity_id">Entity</label>
        <select class="form-control select2 {{ $errors->has('entity_id') ? 'is-invalid' : '' }}" name="entity_id" id="entity_id" required>
          @foreach($entities as $key => $value)
          <option value="{{ $key }}" {{ old('entity_id') == $key ? 'selected' : '' }}>{{ $value }}</option>
          @endforeach
        </select>
        @if($errors->has('entity_id'))
        <span class="text-danger">{{ $errors->first('entity_id') }}</span>
        @endif
      </div>
    </div>
    @endcan
    <div class="col-md-2">
      <div class="form-group">
        <label class="required" for="status">Etat</label>
        <select class="form-control select2 {{ $errors->has('status') ? 'is-invalid' : '' }}" name="status" id="status" required>
          @foreach(App\Objet::STATUS_SELECT as $key => $value)
          <option value="{{ $key }}" {{ old('status') == $key ? 'selected' : '' }}>{{ $value }}</option>
          @endforeach
        </select>
        @if($errors->has('status'))
        <span class="text-danger">{{ $errors->first('status') }}</span>
        @endif
      </div>
    </div>
  </div>
  <div class="form-row">
    <div class="col-md-12">
      <div class="form-group">
        <label class="required" for="name">Objet</label>
        <input class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" type="text" name="name" id="name" value="{{ old('name', '') }}">
        @if($errors->has('name'))
        <span class="text-danger">{{ $errors->first('name') }}</span>
        @endif
      </div>
    </div>

  </div>
  <button type="submit" class="btn btn-danger">
    <span class="fa fa-plus mr-2"></span>Ajouter
  </button>
</x-form>

resources/views/objets/edit.blade.php
<x-form title="Update Objet" :action="route('objets.update',$objet)">
  @method('put')
  <div class="row">
    <div class="col-md-3 d-flex">
      <img src="/svg/{{ $objet->avatar }}" width="100">
    </div>
    <div class="col-md-9">
      <div class="form-row">
        <div class="col-md-4">
          <div class="form-group">
            <label class="required" for="status">Etat</label>
            <select class="form-control select2 {{ $errors->has('status') ? 'is-invalid' : '' }}" name="status" id="status" required>
              @foreach(App\Objet::STATUS_SELECT as $key => $value)
              <option value="{{ $key }}" {{ old('status') == $key ? 'selected' : '' }}>{{ $value }}</option>
              @endforeach
            </select>
            @if($errors->has('status'))
            <span class="text-danger">{{ $errors->first('status') }}</span>
            @endif
          </div>
        </div>
        <div class="col-md-8">
          <div class="form-group">
            <label class="required" for="avatar">Avatar</label>
            <select class="form-control select2 {{ $errors->has('avatar') ? 'is-invalid' : '' }}" name="avatar" id="avatar" required>
              @foreach($avatars as $avatar)
              <option value="{{ $avatar }}" {{ ($avatar == $objet->avatar) ? 'selected' : '' }}>{{ $avatar }}</option>
              @endforeach
            </select>
            @if($errors->has('avatar'))
            <span class="text-danger">{{ $errors->first('avatar') }}</span>
            @endif
          </div>
        </div>
      </div>
      <div class="form-row">
        <div class="col-md-12">
          <div class="form-group">
            <label class="required" for="name">Objet</label>
            <input class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" type="text" name="name" id="name" value="{{ old('name',$objet->name) }}">
            @if($errors->has('name'))
            <span class="text-danger">{{ $errors->first('name') }}</span>
            @endif
          </div>
        </div>
      </div>
      <button type="submit" class="btn btn-dark">
        <span class="fa fa-pen mr-2"></span>Update
      </button>
    </div>
  </div>

</x-form>

resources/views/objets/index.blade.php
<x-data title="La liste des objets" :route="route('objets.create')">

  <table class="table table-sm table-striped datatable">
    <thead>
      <tr>
        <th> Id </th>
        <th> Type </th>
        <th> Objet </th>
        <th> Entité </th>
        <th> Etat </th>
        <th class="actions"> Actions </th>
      </tr>
    </thead>
    <tbody>
      @foreach($objets as $objet)
      <tr data-entry-id="{{ $objet->id }}">
        <td> {{ $objet->id }} </td>
        <td> {{ $objet->type->label }} </td>
        <td> {{ $objet->name }} </td>
        <td> {{ $objet->entity->label }} </td>
        <td> {{ $objet->status }} </td>
        <td>
          <a class="btn btn-xs btn-primary" href="{{ route('objets.subobjets.index',$objet) }}">
            <i class="fas fa-eye"></i>
          </a>
          <a class="btn btn-sm btn-success" href="{{ route('objets.edit', $objet) }}">
            <i class="fas fa-pen"></i>
          </a>
          @can('admin')
          <form action="{{ route('objets.destroy', $objet) }}" method="POST" onsubmit="return confirm('Are you sure?');" style="display: inline-block;">
            @csrf
            @method('delete')
            <button type="submit" class="btn btn-sm btn-danger">
              <i class="fas fa-trash"></i>
            </button>
          </form>
          @endcan
        </td>
      </tr>
      @endforeach
    </tbody>
  </table>

</x-data>

resources/views/objets/show.blade.php
@extends('layouts.admin')
@section('content')
<div class="card">
  <div class="card-header">Détails de l'objet</div>
  <div class="card-body">
    <div class="row">
      <div class="col-md-2">
        <img src="/svg/003.svg" width="100" alt="" />
      </div>
      <div class="col-md-8">
        <dl class="row mb-0">
          <dt class="col-sm-2">Status:</dt>
          <dd class="mb-1 col-sm-9">
            <span class="badge badge-primary badge-md">{{ $objet->status }}</span>
          </dd>
        </dl>

        <dl class="row mb-0">
          <dt class="col-sm-2">Objet:</dt>
          <dd class="mb-1 col-sm-9">{{ $objet->name }}</dd>
        </dl>

        <dl class="row mb-0">
          <dt class="col-sm-2">Entité:</dt>
          <dd class="mb-1 col-sm-9">{{ $objet->entity->label }}</dd>
        </dl>

        <dl class="row mb-0">
          <dt class="col-sm-2">Type d'objet:</dt>
          <dd class="mb-1 col-sm-9">{{ $objet->type->label }}</dd>
        </dl>
      </div>
    </div>
    <div class="mt-3">
      <a name="edit" id="edit" class="btn btn-dark" href="{{ route('objets.subobjets.index',$objet) }}" role="button">Modifier les sous-objets</a>
    </div>
  </div>
</div>
@endsection