routes/web.php
<?php

use App\Http\Controllers\WordController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

// Form Builder
Route::resource('builder', 'BuilderController');

Route::middleware('auth')->group(function () {
    Route::get('/', 'HomeController@index')->name('home');

    Route::resource('shifts', 'ShiftController');

    Route::resource('events', 'EventController');

    Route::get('lines/{status}', 'LineController@index')->where('status', '(live|closed)')->name('lines.status');
    Route::resource('lines', 'LineController');

    Route::get('equipements/{status}', 'EquipementController@index')->where('status', '(live|closed)')->name('equipements.status');
    Route::resource('equipements', 'EquipementController');

    Route::get('/contact-us', 'ContactusController@create')->name('contactus.create');
    Route::post('/contact-us', 'ContactusController@store')->name('contactus.store');

    Route::get('profile', 'ProfileController@show')->name('profile.show');
    Route::put('profile', 'ProfileController@update')->name('profile.update');
    Route::get('password', 'ProfileController@password')->name('profile.password');
    Route::put('password', 'ProfileController@passUpdate')->name('profile.passUpdate');

    Route::middleware('can:supervise')->prefix('supervision')->group(function () {
        Route::get('events', 'SupervisionController@events')->name('supervision.events');
        Route::get('lines', 'SupervisionController@lines')->name('supervision.lines');
        Route::get('equipements', 'SupervisionController@equipements')->name('supervision.equipements');
    });

    Route::prefix('reports')->group(function () {
        Route::view('/tables/lines', 'reports.lines')->name('reports.index');
        Route::get('/tables/data/{objet}', 'ReportController@datatable')->name('reports.data');
        Route::resource('indicators', 'IndicatorController');
        Route::post('indicators/{indicator}', 'IndicatorController@show')->name('reports.data');
    });

    Route::resource('objets', 'ObjetController');
    // Route::resource('subobjets', 'SubobjetController');
    Route::resource('objets.subobjets', 'SubobjetController');
    Route::resource('reports', 'ReportController');
});

Route::middleware('can:admin')->prefix('admin')->group(function () {
    // Messages
    Route::resource('messages', 'MessageController');
    // Route::get('messages', 'ContactusController@index')->name('contactus.index');
    // Users
    Route::resource('users', 'UserController');
    // Entities
    Route::resource('entities', 'EntityController');
    // Roles
    Route::resource('roles', 'RolesController');
    // Abilities
    Route::resource('abilities', 'AbilityController');
    Route::resource('cruds', 'CrudController');
    Route::get("import", "ImportController@create")->name('import.create');
    Route::post("import", "ImportController@parse")->name('import.parse');
    Route::post("import/process", "ImportController@process")->name('import.process');
});

// Route::get('allusers', 'UsersController@datatable');
Auth::routes();

Route::get('/logout', function () {
    Auth::logout();
    return redirect()->route('login');
});

// Route::view('avatarr', 'profiles.avatar');
// Route::view('test', 'test');
Route::get('/indicator/data/{objet}/{year}/{month}', "IndicatorController@data");
Route::view('/lolo', 'login');
Route::get("cmd", "TestController@command");
Route::get("test", "TestController@factors");
Route::view("icons", "pages.icons");
Route::get("add", "ShiftController@add");
Route::view('toto', 'tests.login3');
Route::get('/word', 'WordController@createWordDocument');

app/Equipement.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Equipement extends Model
{
    protected $guarded = ['id'];
    protected $dates = ['start_time', 'end_time'];
    const TYPES_SELECT = ['corr' => 'Corrective', 'prev' => 'Preventive'];

    public function subobjet()
    {
        return $this->belongsTo(Subobjet::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function objet()
    {
        return $this->belongsTo(Objet::class);
    }

    public function entity()
    {
        return $this->belongsTo(Entity::class);
    }
}

app/Http/Controllers/EquipementController.php
<?php

namespace App\Http\Controllers;

use App\Equipement;
use App\Http\Requests\StoreEquipementRequest;
use App\Http\Requests\UpdateEquipementRequest;
use Illuminate\Http\Request;
use Illuminate\Support\Carbon;

class EquipementController extends Controller
{
    private $types = ['corr' => 'Corrective', 'prev' => 'Preventive'];

    public function index(Request $request)
    {
        $equipements = entity()->equipements();

        if ($request->has('objet')) {
            $equipements->where('objet_id', $request->objet);
        }
        if ($request->has('subobjet')) {
            $equipements->where('subobjet_id', $request->subobjet);
        }
        if (request('status') == 'live') $equipements = $equipements->whereNull('end_time');
        $equipements = $equipements->paginate(10);

        return view('equipements.index', compact('equipements'));
    }

    public function create()
    {
        $objets = entity()->objets->where('type_id', 3); /* Select Equipements */
        $subobjets = $objets->first()->subobjets->pluck('name', 'id'); /* Select the first element for select input */
        $objets = $objets->pluck('name', 'id');

        return view('equipements.create', compact('objets', 'subobjets'));
    }

    public function store(StoreEquipementRequest $request)
    {
        $user = me();
        $data = $request->only(['comment', 'subobjet_id', 'type', 'objet_id', 'equipement']);
        $data['user_id'] = $user->id;
        $data['entity_id'] = $user->entity_id;
        $data['start_time'] = "{$request['startdate']} {$request['starttime']}";
        Equipement::create($data);

        return redirect()->route('equipements.index');
    }

    public function show(Equipement $equipement)
    {
        $objets = entity()->objets->where('type_id', 3)->pluck('name', 'id');
        $subobjets = $equipement->objet->subobjets->pluck('name', 'id');

        return view('equipements.close', compact('equipement', 'objets', 'subobjets'));
    }


    public function edit(Equipement $equipement)
    {
        $objets = entity()->objets->where('type_id', 3)->pluck('name', 'id');
        $subobjets = $equipement->objet->subobjets->pluck('name', 'id');

        return view('equipements.edit', compact('equipement', 'objets', 'subobjets'));
    }

    public function update(UpdateEquipementRequest $request, equipement $equipement)
    {
        $user = me();
        $data = $request->only(['comment', 'subobjet_id', 'type', 'objet_id', 'equipement']);
        $data['user_id'] = $user->id;
        $data['entity_id'] = $user->entity_id;
        $data['start_time'] = Carbon::parse("{$request->startdate} {$request->starttime}");

        if (isset($request->endtime) and isset($request->enddate)) {
            $data['end_time'] = Carbon::parse("{$request->enddate} {$request->endtime}");
            $data['duration'] = $data['start_time']->diffInMinutes($data['end_time']);
            $data['status'] = 'closed';
        }

        $equipement->update($data);
        return redirect()->route('equipements.index');
    }


    public function destroy(Equipement $equipement)
    {
        $equipement->delete();
        return redirect()->route('equipements.index');
    }
}

resources/views/equipements/close.blade.php
<x-form icon="/svg/005.svg" :action="route('equipements.update',$equipement)" title="Mise en service des équipements">
  @method('PUT')
  <div class="form-row">
    <div class="form-group col-md-4">
      <label>Objet :</label>
      <select name="objet_id" class="form-control select2" id="objet" placeholder="Selectioner un objet">
        {!! options($objets, $equipement->objet_id) !!}
      </select>
    </div>
    <div class="form-group col-md-4">
      <label>Sous-objet :</label>
      <select class="form-control select2" name="subobjet_id" id="subobj" required>
        {!! options($subobjets, $equipement->subobjet_id) !!}
      </select>
    </div>
    <div class="form-group col-md-4">
      <label>Equipement HS (optionnel) :</label>
      <input type="text" class="form-control" name="equipement" value="{{ $equipement->equipement }}">
    </div>

  </div>
  <div class="hr-fancy"></div>
  <div class="form-row">
    <div class="form-group col-md-4">
      <label>Date d'arrêt:</label>
      <input type="date" class="form-control" name="startdate" value="{{ $equipement->start_time->format('Y-m-d') }}" required>
    </div>
    <div class="form-group col-md-3">
      <label>Heure d'arrêt:</label>
      <input name="starttime" type="time" class="form-control" value="{{ $equipement->start_time->format('H:i') }}" required>
    </div>
  </div>
  <div class="form-row">
    <div class="form-group col-md-4">
      <label>Date de reprise:</label>
      <input type="date" class="form-control" name="enddate" value="{{ date('Y-m-d') }}" required>
    </div>
    <div class="form-group col-md-3">
      <label>Heure de reprise:</label>
      <input name="endtime" type="time" class="form-control" value="{{ date('H:i') }}" required>
    </div>
  </div>
  <div class="form-row">
    <div class="form-group col-md-12">
      <label>Commentaire (optionnelle) :</label>
      <textarea class="form-control" name="comment" rows="3">{{ $equipement->comment }}</textarea>
    </div>
  </div>
  <button type="submit" class="btn btn-dark"><span class="fa fa-play mr-2"></span>Mise en service</button>
</x-form>

resources/views/equipements/create.blade.php
<x-form icon="/svg/005.svg" :action="route('equipements.store')" fa="user" title="Ajouter un équipement HS">
  <div class="form-row">
    <div class="form-group col-md-4">
      <label>Objet :</label>
      <select name="objet_id" class="form-control select2" id="objet" placeholder="Selectioner un objet">
        {!! options($objets) !!}
      </select>
    </div>
    <div class="form-group col-md-4">
      <label>Sous-objet :</label>
      <select class="form-control select2" name="subobjet_id" id="subobj" required>
        {!! options($subobjets) !!}
      </select>
    </div>
    <div class="form-group col-md-4">
      <label>Equipement HS (optionnel) :</label>
      <input type="text" class="form-control" name="equipement">
    </div>

  </div>
  <div class="hr-fancy"></div>
  <div class="form-row">
    <div class="form-group col-md-4">
      <label>Date d'arrêt:</label>
      <input type="date" class="form-control" name="startdate" value="{{date('Y-m-d') }}" required>
    </div>
    <div class="form-group col-md-3">
      <label>Heure d'arrêt:</label>
      <input name="starttime" type="time" class="form-control" value="{{date('H:i') }}" required>
    </div>
  </div>

  <div class="form-row">
    <div class="form-group col-md-12">
      <label>Commentaire (optionnelle) :</label>
      <textarea class="form-control" name="comment" rows="3"></textarea>
    </div>
  </div>

  <button type="submit" class="btn btn-primary"><span class="fa fa-plus mr-2"></span>Ajouter</button>
</x-form>

resources/views/equipements/edit.blade.php
<x-form icon="/svg/005.svg" :action="route('equipements.update',$equipement)" title="Modifer un équipement HS">
  @method('PUT')
  <div class="form-row">
    <div class="form-group col-md-4">
      <label>Objet :</label>
      <select name="objet_id" class="form-control select2" id="objet" placeholder="Selectioner un objet">
        {!! options($objets, $equipement->objet_id) !!}
      </select>
    </div>
    <div class="form-group col-md-4">
      <label>Sous-objet :</label>
      <select class="form-control select2" name="subobjet_id" id="subobj" required>
        {!! options($subobjets, $equipement->subobjet_id) !!}
      </select>
    </div>
    <div class="form-group col-md-4">
      <label>Equipement HS (optionnel) :</label>
      <input type="text" class="form-control" name="equipement" value="{{ $equipement->equipement }}">
    </div>

  </div>
  <div class="hr-fancy"></div>
  <div class="form-row">
    <div class="form-group col-md-4">
      <label>Date d'arrêt:</label>
      <input type="date" class="form-control" name="startdate" value="{{ $equipement->start_time->format('Y-m-d') }}" required>
    </div>
    <div class="form-group col-md-3">
      <label>Heure d'arrêt:</label>
      <input name="starttime" type="time" class="form-control" value="{{ $equipement->start_time->format('H:i') }}" required>
    </div>
  </div>
  @if($equipement->end_time)
  <div class="form-row">
    <div class="form-group col-md-4">
      <label>Date de reprise:</label>
      <input type="date" class="form-control" name="enddate" value="{{ $equipement->end_time->format('Y-m-d') }}" required>
    </div>
    <div class="form-group col-md-3">
      <label>Heure de reprise:</label>
      <input name="endtime" type="time" class="form-control" value="{{ $equipement->end_time->format('H:i') }}" required>
    </div>
  </div>
  @endif
  <div class="form-row">
    <div class="form-group col-md-12">
      <label>Commentaire (optionnelle) :</label>
      <textarea class="form-control" name="comment" rows="3">{{ $equipement->comment }}</textarea>
    </div>
  </div>

  <button type="submit" class="btn btn-success"><span class="fa fa-edit mr-2"></span>Modifier</button>
</x-form>

resources/views/equipements/index.blade.php
@extends('layouts.admin')

@section('title', 'La liste des équipements HS.')

@section('content')
<x-pages-card icon="/svg/005.svg" :link="route('equipements.create')" button="Ajouter un nouveau" :items="$equipements">

  <thead class="">
    <tr>
      <th class="text-center" style="width:200px">Objet</th>
      <th class="text-center" style="width:100px">Debut</th>
      <th class="text-center" style="width:100px">Fin</th>
      <th>Commentaire</th>
      <th class="text-center" style="width:100px">Créé par</th>
      <th class="text-center hide-print" style="width:150px">Actions</th>
    </tr>
  </thead>

  <tbody>
    @foreach ($equipements as $equipement)
    <tr>
      <td class="text-center">
        <a href="{{ route('equipements.index',['objet' => $equipement->objet_id]) }}">{{ $equipement->objet->name }}</a>
        <br />
        <a href="{{ route('equipements.index',['subobjet' => $equipement->subobjet_id]) }}">{{ $equipement->subobjet->name }}</a>
      </td>
      <td class="text-center">
        {{ $equipement->start_time->format("H:i") }}<br />
        <small>{{ $equipement->start_time->format("d-m-Y") }}</small>
      </td>
      <td class="text-center">
        @if($equipement->end_time)
        {{ $equipement->end_time->format("H:i") }}<br />
        <small>{{ $equipement->end_time->format("d-m-Y") }}</small>
        @else
        -----
        @endif
      </td>
      <td class="event text-left p-2">
        @if($equipement->equipement)
        <span class="badge badge-info">{{ $equipement->equipement }}</span>
        @endif
        {!! markdown($equipement->comment,false) !!}
      </td>
      <td class="text-center">
        <span class="badge badge-dark text-sm">
          {{ $equipement->user->username }}
        </span>
      </td>
      <td class="text-center hide-print">
        @unless($equipement->end_time)
        <a class="btn btn-success btn-sm" href="{{ route('equipements.show',$equipement) }}" title="Mise en service">
          <i class="fas fa-check-circle"></i>
        </a>
        @endunless
        <a class="btn btn-info btn-sm" href="{{ route('equipements.edit',$equipement) }}" title="Éditer">
          <i class="fas fa-pencil-alt"></i>
        </a>
        <a class="btn btn-danger btn-sm" title="Supprimer" href="#" data-url="{{ route('equipements.destroy',$equipement) }}" onclick="deleteData(this)" title="Supprimer">
          <i class="fas fa-trash"></i>
        </a>
      </td>
    </tr>
    @endforeach
  </tbody>
</x-pages-card>
@endsection