routes/web.php
<?php

use App\Http\Controllers\WordController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

// Form Builder
Route::resource('builder', 'BuilderController');

Route::middleware('auth')->group(function () {
    Route::get('/', 'HomeController@index')->name('home');

    Route::resource('shifts', 'ShiftController');

    Route::resource('events', 'EventController');

    Route::get('lines/{status}', 'LineController@index')->where('status', '(live|closed)')->name('lines.status');
    Route::resource('lines', 'LineController');

    Route::get('equipements/{status}', 'EquipementController@index')->where('status', '(live|closed)')->name('equipements.status');
    Route::resource('equipements', 'EquipementController');

    Route::get('/contact-us', 'ContactusController@create')->name('contactus.create');
    Route::post('/contact-us', 'ContactusController@store')->name('contactus.store');

    Route::get('profile', 'ProfileController@show')->name('profile.show');
    Route::put('profile', 'ProfileController@update')->name('profile.update');
    Route::get('password', 'ProfileController@password')->name('profile.password');
    Route::put('password', 'ProfileController@passUpdate')->name('profile.passUpdate');

    Route::middleware('can:supervise')->prefix('supervision')->group(function () {
        Route::get('events', 'SupervisionController@events')->name('supervision.events');
        Route::get('lines', 'SupervisionController@lines')->name('supervision.lines');
        Route::get('equipements', 'SupervisionController@equipements')->name('supervision.equipements');
    });

    Route::prefix('reports')->group(function () {
        Route::view('/tables/lines', 'reports.lines')->name('reports.index');
        Route::get('/tables/data/{objet}', 'ReportController@datatable')->name('reports.data');
        Route::resource('indicators', 'IndicatorController');
        Route::post('indicators/{indicator}', 'IndicatorController@show')->name('reports.data');
    });

    Route::resource('objets', 'ObjetController');
    // Route::resource('subobjets', 'SubobjetController');
    Route::resource('objets.subobjets', 'SubobjetController');
    Route::resource('reports', 'ReportController');
});

Route::middleware('can:admin')->prefix('admin')->group(function () {
    // Messages
    Route::resource('messages', 'MessageController');
    // Route::get('messages', 'ContactusController@index')->name('contactus.index');
    // Users
    Route::resource('users', 'UserController');
    // Entities
    Route::resource('entities', 'EntityController');
    // Roles
    Route::resource('roles', 'RolesController');
    // Abilities
    Route::resource('abilities', 'AbilityController');
    Route::resource('cruds', 'CrudController');
    Route::get("import", "ImportController@create")->name('import.create');
    Route::post("import", "ImportController@parse")->name('import.parse');
    Route::post("import/process", "ImportController@process")->name('import.process');
});

// Route::get('allusers', 'UsersController@datatable');
Auth::routes();

Route::get('/logout', function () {
    Auth::logout();
    return redirect()->route('login');
});

// Route::view('avatarr', 'profiles.avatar');
// Route::view('test', 'test');
Route::get('/indicator/data/{objet}/{year}/{month}', "IndicatorController@data");
Route::view('/lolo', 'login');
Route::get("cmd", "TestController@command");
Route::get("test", "TestController@factors");
Route::view("icons", "pages.icons");
Route::get("add", "ShiftController@add");
Route::view('toto', 'tests.login3');
Route::get('/word', 'WordController@createWordDocument');

app/Subobjet.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Subobjet extends Model
{
    protected $guarded = ['id'];
    public function objet()
    {
        return $this->belongsTo(Objet::class);
    }

    public function lines()
    {
        return $this->hasMany(Line::class);
    }
}

app/Http/Controllers/SubobjetController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Http\Requests\StoreSubobjetRequest;
use App\Objet;
use App\Subobjet;

class SubobjetController extends Controller
{
    public function index(Objet $objet)
    {
        $subobjets = $objet->subobjets->all();
        return view('subobjets.index', compact('subobjets', 'objet'));
    }

    public function create(Objet $objet)
    {
        return view('subobjets.create', compact('objet'));
    }

    public function store(StoreSubobjetRequest $request, Objet $objet)
    {
        $subobjet = $objet->subobjets()->create($request->all());
        return redirect()->route('objets.subobjets.index', $objet);
    }

    public function edit(Objet $objet, Subobjet $subobjet)
    {
        // return $subobjet;
        return view('subobjets.edit', compact('subobjet', 'objet'));
    }

    public function update(StoreSubobjetRequest $request, Objet $objet, Subobjet $subobjet)
    {
        $subobjet->update($request->all());
        return redirect()->route('objets.subobjets.index', $objet);
    }

    public function show(Subobjet $subobjet)
    {
        return view('subobjets.show', compact('subobjet'));
    }

    public function destroy(Objet $objet, Subobjet $subobjet)
    {
        $subobjet->delete();
        return back();
    }
}

resources/views/subobjets/create.blade.php
<x-form title="Créer un nouveau sous-objet" :action="route('objets.subobjets.store',$objet)">
  <div class="form-group">
    <label class="required" for="name">Sous-objet</label>
    <input class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" type="text" name="name" id="name" value="{{ old('name', '') }}">
    @if($errors->has('name'))
    <span class="text-danger">{{ $errors->first('name') }}</span>
    @endif
  </div>
  <div class="form-group">
    <label for="description">Description</label>
    <input class="form-control {{ $errors->has('description') ? 'is-invalid' : '' }}" type="text" name="description" id="description" value="{{ old('description', '') }}">
    @if($errors->has('description'))
    <span class="text-danger">{{ $errors->first('description') }}</span>
    @endif
  </div>

  <button type="submit" class="btn btn-dark">
    <span class="fa fa-plus mr-2"></span>Ajouter
  </button>
</x-form>

resources/views/subobjets/edit.blade.php
<x-form title="Modifier un sous-objet" :action="route('objets.subobjets.update',[$objet,$subobjet])">
  @method('put')
  <div class="form-group">
    <label class="required" for="name">Sous-objet</label>
    <input class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" type="text" name="name" id="name" value="{{ old('name', $subobjet->name) }}" />
    @if($errors->has('name'))
    <span class="text-danger">{{ $errors->first('name') }}</span>
    @endif
  </div>
  <div class="form-group">
    <label for="description">Description</label>
    <input class="form-control {{ $errors->has('description') ? 'is-invalid' : '' }}" type="text" name="description" id="description" value="{{ old('description', $subobjet->description) }}" />
    @if($errors->has('description'))
    <span class="text-danger">{{ $errors->first('description') }}</span>
    @endif
  </div>

  <button type="submit" class="btn btn-danger">
    <span class="fa fa-pen mr-2"></span>Modifier
  </button>
</x-form>

resources/views/subobjets/index.blade.php
<x-data :title="'La liste des sous-objets de ' . $objet->name" :route="route('objets.subobjets.create',$objet)">
  @section('before')
  <div class="card">
    <div class="card-header">Détails de l'objet</div>
    <div class="card-body">
      <div class="row">
        <div class="col-md-2">
          <img src="/svg/{{ $objet->avatar }}" width="100" alt="" />
        </div>
        <div class="col-md-8">
          <dl class="row mb-0">
            <dt class="col-sm-2">Status:</dt>
            <dd class="mb-1 col-sm-9">
              <span class="badge badge-primary badge-md">{{ $objet->status }}</span>
            </dd>
          </dl>

          <dl class="row mb-0">
            <dt class="col-sm-2">Objet:</dt>
            <dd class="mb-1 col-sm-9">{{ $objet->name }}</dd>
          </dl>

          <dl class="row mb-0">
            <dt class="col-sm-2">Entité:</dt>
            <dd class="mb-1 col-sm-9">{{ $objet->entity->label }}</dd>
          </dl>

          <dl class="row mb-0">
            <dt class="col-sm-2">Type d'objet:</dt>
            <dd class="mb-1 col-sm-9">{{ $objet->type->label }}</dd>
          </dl>
        </div>
      </div>
    </div>
  </div>
  @endsection

  <table class="table table-sm table-striped datatable">
    <thead>
      <tr>
        <th> Objet </th>
        <th> Sous-objet </th>
        <th> Description </th>
        <th> Etat </th>
        <th> Actions </th>
      </tr>
    </thead>
    <tbody>
      @foreach($subobjets as $subobjet)
      <tr data-entry-id="{{ $subobjet->id }}">
        <td> {{ $objet->name }} </td>
        <td> {{ $subobjet->name }} </td>
        <td> {{ $subobjet->description }} </td>
        <td> {{ $subobjet->status }} </td>
        <td>
          <a class="btn btn-xs btn-primary" href="{{ route('objets.subobjets.show', [$objet,$subobjet]) }}">
            <i class="fas fa-eye"></i>
          </a>
          <a class="btn btn-sm btn-success" href="{{ route('objets.subobjets.edit', [$objet,$subobjet]) }}">
            <i class="fas fa-pen"></i>
          </a>
          <form action="{{ route('objets.subobjets.destroy', [$objet,$subobjet]) }}" method="POST" onsubmit="return confirm('Are you sure?');" style="display: inline-block;">
            @csrf
            @method('delete')
            <button type="submit" class="btn btn-sm btn-danger">
              <i class="fas fa-trash"></i>
            </button>
          </form>
        </td>
      </tr>
      @endforeach
    </tbody>
  </table>

</x-data>

resources/views/subobjets/show.blade.php
@extends('layouts.admin')

@section('content')
<div class="card">
  <div class="card-header">Show View</div>
  <div class="card-body">

  </div>
</div>
@endsection